package com.originlang.onlysql;

import com.originlang.onlysql.jdbc.H2DataSources;
import com.originlang.onlysql.jdbc.JdbcDmlExecutor;
import com.originlang.onlysql.sql.ExecutorContext;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * 测试用 H2 连接与表初始化，供 onlysql-example 中测试连接 H2 使用。
 */
public final class H2TestSupport {

    private static final String CREATE_SYS_USER = ""
            + "CREATE TABLE IF NOT EXISTS sys_user ("
            + "  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            + "  username VARCHAR(255),"
            + "  age INT,"
            + "  create_time TIMESTAMP,"
            + "  update_time TIMESTAMP,"
            + "  create_by BIGINT,"
            + "  update_by BIGINT,"
            + "  revision INT"
            + ")";

    private H2TestSupport() {
    }

    /**
     * 创建内存 H2 DataSource（库名 example），并设置为当前线程的 DmlExecutor。
     */
    public static DataSource initH2AndExecutor() {
        DataSource ds = H2DataSources.inMemory("example");
        ExecutorContext.setExecutor(new JdbcDmlExecutor(ds));
        return ds;
    }

    /**
     * 创建 sys_user 表（若不存在）。
     */
    public static void createSysUserTable(DataSource dataSource) throws SQLException {
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.execute(CREATE_SYS_USER);
        }
    }

    /**
     * 初始化 H2 内存库、设置 ExecutorContext、并创建 sys_user 表。
     */
    public static DataSource initH2WithSysUser() throws SQLException {
        DataSource ds = initH2AndExecutor();
        createSysUserTable(ds);
        return ds;
    }
}
