package com.originlang.onlysql.jdbc;

import jakarta.persistence.Column;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Version;

import java.lang.reflect.Field;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * 根据 @Entity / @Table / @Column 生成 CREATE TABLE SQL，适合测试或简单迁移；生产建议用专业迁移工具。
 * <p>
 * 类型映射按 H2/常见数据库：String→VARCHAR(255)，Long→BIGINT，Integer→INT，LocalDateTime→TIMESTAMP 等。
 */
public final class EntityDdlBuilder {

    private static final int DEFAULT_VARCHAR_LENGTH = 255;

    private EntityDdlBuilder() {
    }

    /**
     * 生成 CREATE TABLE 语句。
     *
     * @param entityClass  带 @Entity 的实体类（含父类字段）
     * @param ifNotExists  是否带 IF NOT EXISTS
     * @return 完整 CREATE TABLE SQL
     */
    public static String buildCreateTableSql(Class<?> entityClass, boolean ifNotExists) {
        String tableName = getTableName(entityClass);
        List<ColumnSpec> columns = collectColumns(entityClass);
        if (columns.isEmpty()) {
            throw new IllegalArgumentException("实体无持久化字段: " + entityClass.getName());
        }
        StringBuilder sql = new StringBuilder("CREATE TABLE ");
        if (ifNotExists) {
            sql.append("IF NOT EXISTS ");
        }
        sql.append(quoteIdentifier(tableName)).append(" (");
        List<String> parts = new ArrayList<>();
        for (ColumnSpec col : columns) {
            parts.add(toColumnDdl(col));
        }
        sql.append(String.join(", ", parts)).append(")");
        return sql.toString();
    }

    private static String getTableName(Class<?> entityClass) {
        Table t = entityClass.getAnnotation(Table.class);
        if (t != null && t.name() != null && !t.name().isEmpty()) {
            return t.name();
        }
        return camelToSnake(entityClass.getSimpleName());
    }

    private static List<ColumnSpec> collectColumns(Class<?> type) {
        Map<String, ColumnSpec> byName = new LinkedHashMap<>();
        Class<?> current = type;
        while (current != null && current != Object.class) {
            for (Field f : current.getDeclaredFields()) {
                if (java.lang.reflect.Modifier.isStatic(f.getModifiers())) continue;
                String columnName = getColumnName(f);
                String typeDdl = mapType(f.getType(), f);
                boolean isId = f.getAnnotation(Id.class) != null;
                boolean isVersion = f.getAnnotation(Version.class) != null;
                Column col = f.getAnnotation(Column.class);
                int length = col != null && col.length() > 0 ? col.length() : DEFAULT_VARCHAR_LENGTH;
                boolean nullable = col == null || col.nullable();
                byName.putIfAbsent(columnName, new ColumnSpec(columnName, typeDdl, isId, isVersion, length, nullable));
            }
            current = current.getSuperclass();
        }
        return new ArrayList<>(byName.values());
    }

    private static String getColumnName(Field f) {
        Column c = f.getAnnotation(Column.class);
        if (c != null && c.name() != null && !c.name().isEmpty()) {
            return c.name();
        }
        return camelToSnake(f.getName());
    }

    private static String mapType(Class<?> type, Field f) {
        if (type == long.class || type == Long.class) return "BIGINT";
        if (type == int.class || type == Integer.class) return "INT";
        if (type == short.class || type == Short.class) return "SMALLINT";
        if (type == boolean.class || type == Boolean.class) return "BOOLEAN";
        if (type == String.class) {
            Column c = f.getAnnotation(Column.class);
            int len = c != null && c.length() > 0 ? c.length() : DEFAULT_VARCHAR_LENGTH;
            return "VARCHAR(" + len + ")";
        }
        if (type == java.util.Date.class || type == java.sql.Timestamp.class) return "TIMESTAMP";
        if (type == java.sql.Date.class) return "DATE";
        if (type == LocalDateTime.class) return "TIMESTAMP";
        if (type == LocalDate.class) return "DATE";
        if (type == LocalTime.class) return "TIME";
        return "VARCHAR(" + DEFAULT_VARCHAR_LENGTH + ")";
    }

    private static String toColumnDdl(ColumnSpec col) {
        StringBuilder sb = new StringBuilder(quoteIdentifier(col.columnName)).append(" ").append(col.typeDdl);
        if (col.id) {
            sb.append(" GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
        } else {
            if (!col.nullable) sb.append(" NOT NULL");
        }
        return sb.toString();
    }

    private static String quoteIdentifier(String name) {
        return "\"" + name.replace("\"", "\"\"") + "\"";
    }

    private static String camelToSnake(String camel) {
        if (camel == null || camel.isEmpty()) return camel;
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < camel.length(); i++) {
            char c = camel.charAt(i);
            if (Character.isUpperCase(c)) {
                if (i > 0) sb.append('_');
                sb.append(Character.toLowerCase(c));
            } else {
                sb.append(c);
            }
        }
        return sb.toString();
    }

    private static final class ColumnSpec {
        final String columnName;
        final String typeDdl;
        final boolean id;
        final boolean version;
        final int length;
        final boolean nullable;

        ColumnSpec(String columnName, String typeDdl, boolean id, boolean version, int length, boolean nullable) {
            this.columnName = columnName;
            this.typeDdl = typeDdl;
            this.id = id;
            this.version = version;
            this.length = length;
            this.nullable = nullable;
        }
    }
}
